### ISSUE TITLE
'redux-form-material-ui' not resolved

### ISSUE THREAD

**Issue by oreqizer** [oreqizer/reactizer-2016#12]
Dunno why this happens, meanwhile turning off `eslint` there for travis until I resolve it.

**Comment by erikras** [comment]
Pretty bizarre. It's like it's not running an `npm install` before it's doing the linting.

Anyway, sorry for introducing a bug into your system. 😅

**Comment by oreqizer** [comment]
it actually happens to me locally too for some reason, wasn't able to fix it yet. I'll have a look at it again this evening

it's ok, solved bugs make us stronger

**Comment by oreqizer** [comment]
https://david-dm.org/oreqizer/reactizer I noticed this dep checker has problems with revision difference, too

i'll just echo the eslint guys if they know what's up

**Comment by oreqizer** [comment]
not using the dep anymore - closing
